#!/bin/bash
sourcepath=/home/rink/Desktop/RestService_so/so
librarypath=/usr/lib
programpath=/home/rink/Desktop/RestService_so
sudo rm $librarypath/librestService.so
cd $sourcepath
sudo rm librestService.so
g++ -std=c++11 -fPIC -c ./RestCallClient.cpp ./ServiceStruct/EnaviBase.cpp ./ServiceStruct/VesselStaticInfo.cpp ./ServiceStruct/sv10/abnormalPattern.cpp ./ServiceStruct/sv10/AccidentPrediction.cpp ./ServiceStruct/sv10/AccidentRisk.cpp ./ServiceStruct/sv10/areaDetail.cpp ./ServiceStruct/sv10/areaMst.cpp ./ServiceStruct/sv10/areaSelect.cpp ./ServiceStruct/sv10/AttentionShip.cpp ./ServiceStruct/sv10/avsResponse.cpp ./ServiceStruct/sv10/DangerShipAlarm.cpp ./ServiceStruct/sv10/fishingHistoryArea.cpp ./ServiceStruct/sv10/fishingPatternArea.cpp ./ServiceStruct/sv10/rssResponse.cpp ./ServiceStruct/sv10/SpecThreshold.cpp ./ServiceStruct/sv10/vulInput00_1.cpp ./ServiceStruct/sv10/vulInput00_2.cpp ./ServiceStruct/sv10/vulInput01.cpp ./ServiceStruct/sv10/vulInput02.cpp ./ServiceStruct/sv10/vulInput03.cpp ./ServiceStruct/sv10/vulInput04.cpp ./ServiceStruct/sv10/vulInput05.cpp ./ServiceStruct/sv10/vulInput06.cpp ./ServiceStruct/sv10/vulInput07.cpp ./ServiceStruct/sv30/FTS.cpp ./ServiceStruct/sv30/PastNavInfo.cpp ./ServiceStruct/sv30/PastNavVesselInfo.cpp ./ServiceStruct/sv30/Route.cpp ./ServiceStruct/sv30/RouteInfo.cpp ./ServiceStruct/sv30/Schedules.cpp ./ServiceStruct/sv30/Waypoints.cpp ./ServiceStruct/sv40/Catalogue.cpp ./ServiceStruct/sv40/CatalogueAll.cpp ./ServiceStruct/sv40/EncUpdate.cpp ./ServiceStruct/sv40/S57Cell.cpp ./ServiceStruct/sv40/S101Cell.cpp ./ServiceStruct/sv40/Zone.cpp ./ServiceStruct/sv40/ZoneAll.cpp ./ServiceStruct/sv40/ZoneAllDel.cpp ./ServiceStruct/sv40/MrnRecentVersion.cpp ./ServiceStruct/sv51/GuideLine.cpp ./ServiceStruct/sv51/GuideLineAnchorage.cpp ./ServiceStruct/sv51/GuideLineCourse.cpp ./ServiceStruct/sv51/GuideLineFairway.cpp ./ServiceStruct/sv51/GuideLineInfo.cpp ./ServiceStruct/sv51/GuideLinePilot.cpp ./ServiceStruct/sv51/GuideLinePoint.cpp ./ServiceStruct/sv51/GuideLineSafetySpeed.cpp ./ServiceStruct/sv51/GuideLineSafetyStan.cpp ./ServiceStruct/sv51/GuideLineSpeed.cpp ./ServiceStruct/sv51/GuideLineTug.cpp ./ServiceStruct/sv51/GuideLineVTS.cpp ./ServiceStruct/sv51/GuideLineWharf.cpp ./ServiceStruct/sv51/ShipPosition.cpp ./ServiceStruct/sv51/ShipDensity.cpp ./ServiceStruct/sv20/nested/NavigationInfo.cpp ./ServiceStruct/sv20/nested/EmergencyInfo.cpp ./ServiceStruct/sv20/nested/FireDoor.cpp ./ServiceStruct/sv20/nested/FireAlarm.cpp ./ServiceStruct/sv20/nested/OldFireAlarm.cpp ./ServiceStruct/sv20/nested/MainEngine.cpp ./ServiceStruct/sv20/nested/Generator.cpp ./ServiceStruct/sv20/nested/SteeringGear.cpp ./ServiceStruct/sv20/nested/Recovery.cpp ./ServiceStruct/sv20/nested/TankLevel.cpp ./ServiceStruct/sv20/nested/Ramp.cpp ./ServiceStruct/sv20/nested/Telegraph.cpp ./ServiceStruct/sv20/nested/Stability.cpp ./ServiceStruct/sv20/ShipStaticInfo.cpp ./ServiceStruct/sv52/ArgoMet.cpp ./ServiceStruct/sv52/FeaturesForWaterway.cpp ./ServiceStruct/common/ServiceLog.cpp ./ServiceStruct/EncSelector.cpp ./RestClientManager.cpp ./ExportRestFunc.cpp -L./usr/local/boost_1_66_0 -lboost_system -lcrypto -lssl -lcpprest -lpthread
g++ -shared -\I -W1,-soname,librestService.so -lboost_system -lcrypto -lssl -lcpprest -lpthread -o librestService.so.1.0.0 EnaviBase.o VesselStaticInfo.o abnormalPattern.o AccidentPrediction.o AccidentRisk.o areaDetail.o areaMst.o areaSelect.o AttentionShip.o avsResponse.o DangerShipAlarm.o fishingHistoryArea.o fishingPatternArea.o rssResponse.o SpecThreshold.o vulInput00_1.o vulInput00_2.o vulInput01.o vulInput02.o vulInput03.o vulInput04.o vulInput05.o vulInput06.o vulInput07.o FTS.o PastNavInfo.o PastNavVesselInfo.o Route.o RouteInfo.o Schedules.o Waypoints.o Catalogue.o EncUpdate.o S57Cell.o S101Cell.o Zone.o ZoneAll.o ZoneAllDel.o MrnRecentVersion.o GuideLine.o GuideLineAnchorage.o GuideLineCourse.o CatalogueAll.o GuideLineFairway.o GuideLineInfo.o GuideLinePilot.o GuideLinePoint.o GuideLineSafetySpeed.o GuideLineSafetyStan.o GuideLineSpeed.o GuideLineTug.o GuideLineVTS.o GuideLineWharf.o ShipPosition.o ShipDensity.o NavigationInfo.o EmergencyInfo.o FireDoor.o FireAlarm.o OldFireAlarm.o MainEngine.o Generator.o SteeringGear.o Recovery.o TankLevel.o Ramp.o Telegraph.o Stability.o ShipStaticInfo.o ArgoMet.o FeaturesForWaterway.o RestCallClient.o  ServiceLog.o EncSelector.o RestClientManager.o ExportRestFunc.o
ln -s librestService.so.1.0.0 librestService.so
sudo cp ./librestService.so /usr/lib/librestService.so
cd $programpath
g++ -std=c++11 -L/usr/lib ResultRenderer.cpp ProgressMNG.cpp main.cpp -o main -Wall -ldl -lboost_system -lcrypto -lssl -lpthread -lrestService -lcpprest
exit 0
